# Simulação de Monte Carlo
## Código de Hamming (7,4)


O código de Hamming (7,4) toma um bloco de quatro bits de dados e acrescenta três bits de paridade da seguinte forma

$\begin{bmatrix} d_1 & d_2 & d_3 & d_4 & p_1 & p_2 & p_3 \end{bmatrix}$

em que $d_i, \quad i=1,2,3,4$ representam os dados de informação e $p_i, \quad i=1,2,3$ representam os bits de paridade calculados da seguinte forma

$p_1 = d_1 \oplus d_2 \oplus d_4$

$p_2 = d_1 \oplus d_3 \oplus d_4$

$p_3 = d_2 \oplus d_3 \oplus d_4$

Isso pode ser feito utilizando-se uma matriz geradoro $G$ da seguinte forma $C = GD \quad \mod 2$ em que 

$G = \begin{bmatrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \\
                    1 & 1 & 0 & 1 \\ 1 & 0 & 1 & 1 \\ 0 & 1 & 1 & 1 \end{bmatrix}$
                    
e $D = \begin{bmatrix} d_1 & d_2 & d_3 & d_4  \end{bmatrix}^T$





Pretende-se simular um sistema de comunicações simples utilizando utilizando o código de Hamming (7,4) para correção de erros.

In [1]:
"""
@author: albert
IQuanta - DEE - UFCG
Data: junho 2022
Versão: 1.0
"""

import random
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Gerar blocos de quatro bits informação aleatório
def gerador():
    x=[]              ## lista vazia
    for i in range (4):
        random.seed()
        x.append(random.randint(0,1))
    return x

In [33]:
Info = gerador() # bits de informação
print(Info)

[0, 0, 0, 1]


In [4]:
# Codificador de Hamming (7,4)
def cod_hamming(d):
    # matriz geradora transposta
    GT = np.array([[1,0,0,0,1,1,0],[0,1,0,0,1,0,1],[0,0,1,0,0,1,1],[0,0,0,1,1,1,1]])
    # print(GT)
    C = d @ GT
    return(C%2)

In [36]:
C_Hamming = cod_hamming(Info)
print(C_Hamming)

[0 0 0 1 1 1 1]


## Descodificação

O código de Hamming (7,4) permite a correção de um até um erro na transmissão de uma palavra código. Considere $C\_Hamming$ a palavra código transmitida e $Rec$ a palavra código recebida depois de passar por um canal ruidoso. Podemos escrever a palavra recebida como

$Rec = C\_Hamming \oplus Erro$

em que $Erro$ é um vetor de erro, por exemplo, caso não haja erro na transmissão $Erro = \begin{bmatrix} 0 & 0 & 0 & 0 & 0 & 0 & 0 \end{bmatrix}$ e a palavra código transmitida será igual a palavra recebida, caso haja um erro no segundo bit então o vetor erro seria $Erro = \begin{bmatrix} 0 & 1 & 0 & 0 & 0 & 0 & 0 \end{bmatrix}$.

Temos que pela construção do código um vetor de síndrome da seguinte forma

$p_1 = d_1 \oplus d_2 \oplus d_4$

$p_2 = d_1 \oplus d_3 \oplus d_4$

$p_3 = d_2 \oplus d_3 \oplus d_4$

Para verificar se as paridades da palavra código recebida $Rec$ estão corretas, construímos um vetor de síndrome $Sindrome = \begin{bmatrix} s_1 & s_2 & s_3 \end{bmatrix}$ da seguinte forma

$s_1 = p_1 \oplus d_1 \oplus d_2 \oplus d_4$

$s_2 = p_2 \oplus d_1 \oplus d_3 \oplus d_4$

$s_3 = p_3 \oplus d_2 \oplus d_3 \oplus d_4$

Quando $Sindrome = \begin{bmatrix} 0 & 0 & 0 \end{bmatrix}$ podemos concluir que não houve erro na transmissão ou que houveram erros suficientes para transforma a palavra código tranmitida em uma outra palavra código válida que também produz o vetor de síndrome zero. Tomando $Rec = \begin{bmatrix} 0 & 1 & 0 & 1 & 0 & 1 & 0 \end{bmatrix}$ verificamos que 

$s_1 = 0 \oplus 0 \oplus 1 \oplus 1 = 0$

$s_2 = 1 \oplus 0 \oplus 0 \oplus 1 = 0$

$s_3 = 0 \oplus 1 \oplus 0 \oplus 1 = 0$

estimamos então que os dados de informação foram $Info = \begin{bmatrix} 0 & 1 & 0 & 1 \end{bmatrix}$ 

Considerando que o vetor erro seria $Erro = \begin{bmatrix} 0 & 1 & 0 & 0 & 0 & 0 & 0 \end{bmatrix}$ então a palavra código recebida seria $Rec = \begin{bmatrix} 0 & 0 & 0 & 1 & 0 & 1 & 0 \end{bmatrix}$ e o vetor sindrome seria

$s_1 = 0 \oplus 0 \oplus 0 \oplus 1 = 1$

$s_2 = 1 \oplus 0 \oplus 0 \oplus 1 = 0$

$s_3 = 0 \oplus 0 \oplus 0 \oplus 1 = 1$

$Sindrome = \begin{bmatrix} 1 & 0 & 1 \end{bmatrix}$ indicando que algo está errado, examinando os resultados vemos que $s_2 = 0$ então os bits $p_2,d_1,d_3, d_4$ devem estar corretos , por $s_1$ os bits errados podem ser $p1$ ou $d_2$, por $s_3$ os bits errados podem ser $p3$ ou $d_2$ e portando o bit errado deve ser $d_2$, pois modificando ele o vetor síndrome é zerado. Estimamos, então, que os dados de informação foram $Info = \begin{bmatrix} 0 & 1 & 0 & 1 \end{bmatrix}$ 

A sindrome também pode ser calculada através da matris de paridade $H$ em que os 1's das linhas da matriz correspondem aos valores calculados nas sindromes, assim a primeira linha é um em $d_1,d_2,d_4,p_1$ a segunda linha em $d_1,d_2,d_4,p_2$ e a terceira linha em $d_2,d_3,d_4,p_3$ de modo que

$Sindrome = H.Rec^T = \begin{bmatrix} 1 & 1 & 0 & 1 & 1 & 0 & 0 \\ 1 & 0 & 1 & 1 & 0 & 1 & 0 \\ 0 & 1 & 1 & 1 & 0 & 0 & 1 \end{bmatrix}Rec^T$

em que $Rec^T$ é a transposta de $Rec$, ou seja um vetor coluna. Observe que a síndrome $Sindrome = \begin{bmatrix} 1 & 0 & 1 \end{bmatrix}$  correponde a segunda linha da matriz $H$ indicando que o bit $d_2$ é o que está errado e correponde a $H.Erro^T$

In [27]:
def descodificador(r): # r é a palavra código recebida
    print(r)
    # matriz de paridade H
    H = np.array([[1,1,0,1,1,0,0],[1,0,1,1,0,1,0],[0,1,1,1,0,0,1]])
    Sindrome = (H @ r.T)%2
    print(Sindrome)
    
    # Cálculo do vetor erro ou da posição da síndrome na matriz H que indica onde o erro ocorreu.
    
    # inicializa o vetor erro com zeros
    Erro = []
    for k in range(7):
        Erro.append(0)
    
    Erro[0] = Sindrome[0] & Sindrome[1] & (Sindrome[2] ^ 1)
    Erro[1] = Sindrome[0] & (Sindrome[1] ^ 1) & Sindrome[2]
    Erro[2] = (Sindrome[0] ^ 1) & Sindrome[1] & Sindrome[2]
    Erro[3] = Sindrome[0] & Sindrome[1] & Sindrome[2]
    Erro[4] = Sindrome[0] & (Sindrome[1] ^ 1) & (Sindrome[2] ^ 1)
    Erro[5] = (Sindrome[0] ^ 1) & Sindrome[1] & (Sindrome[2] ^ 1)
    Erro[6] = (Sindrome[0] ^ 1) & (Sindrome[1] ^ 1) & Sindrome[2]
    print(Erro)
    
    # Estimação da palavra código enviada
    Cod_estimado = []
    for k in range(7):
        Cod_estimado.append(r[k] ^ Erro[k])
    print(Cod_estimado)
    
    # Estimação da informação enviada (os 4 primeiros bits da palavra código estimada)
    Dados_estimados = []
    for k in range(4):
        Dados_estimados.append(Cod_estimado[k])
    print(Dados_estimados)
    
    return(Dados_estimados)

In [37]:
C_Hamming[6] = C_Hamming[6] ^ 1 # introduz um erro no segundo bit
descodificador(C_Hamming)

[0 0 0 1 1 1 0]
[0 0 1]
[0, 0, 0, 0, 0, 0, 1]
[0, 0, 0, 1, 1, 1, 1]
[0, 0, 0, 1]


[0, 0, 0, 1]